### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by HediaTnani** [jhudsl/ari#27]
Hi,
I'l getting this error when running ari.
`ari_narrate("Introduction_to_R.Rmd","Introduction_to_R.html",voice = "Kendra",
            delay = 0.5,
            capture_method = "iterative")`
Could not load  file:///C:/Documents/file:/localhost/C:/Documents/Introduction_to_R.html#1
Error in webshot(url = paste0(slides, "#", i), file = img_paths[i], ...) : 
  webshot.js returned failure value: 1
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="file://localhost/C:\Documents\Introduction_to_R.html#1": The filename, directory name, or volume label syntax is incorrect

I'm using windows. Is there a way to fix it?

Thanks a lot.

**Comment by muschellij2** [comment]
Can you try to reinstall using `remotes::install_github("jhudsl/ari")` and try to rerun?
