### ISSUE TITLE
Cannot sign in R studio

### ISSUE THREAD

**Issue by kokitsuyuzaki** [jhudsl/ari#28]
Thanks for interesting attempt. 

I tried to follow the vignette of ari but I couldn't sign in R studio server with username/pass written in the vignette.
https://cran.r-project.org/web/packages/ari/vignettes/Simple-Ari-Configuration-with-Docker.html
Could you check that?

**Comment by seankross** [comment]
Hey sorry this is my fault! The username is `rstudio` and the password is `ari`. I will make sure to change the docs. Thanks!

**Comment by kokitsuyuzaki** [comment]
Thanks!!!
