### ISSUE TITLE
Beamer presentation compatibility

### ISSUE THREAD

**Issue by sebacea** [jhudsl/ari#30]
Is there a way to have beamer presentations narrated by ari?

**Comment by muschellij2** [comment]
Since beamer compiles to PDF, then you should be able to PDF → PNG using `pdftools::pdf_convert` and then pass the resulting PNG files into `images` argument of `ari_spin`.  

How do you see the "script" embedded in the beamer?  In comments or some other notes area?  Please reopen if that's clear.

**Comment by sebacea** [comment]
I understood the method in order to narrate beamers presentations. Nevertheless, I did not get the point regarding the embedded script you say.
