### ISSUE TITLE
Unable to use animations on xaringan presentations

### ISSUE THREAD

**Issue by mgkulik** [jhudsl/ari#31]
I was able to use xarigan to generate my videos, but when I add slide transitions or animated gifs to the presentation, they seam to be ignored by ari and are not replicated to the video.

Slide transitions and gifs are working perfectly in the HTML presentation.

To generate animated plots I used gganimate and for slide transitions I followed the steps suggested in this link: https://www.garrickadenbuie.com/blog/animate-xaringan-slide-transitions/

Do I need to set any specific parameter on ari for the animations to work or it doesn't currently support animations?

**Comment by muschellij2** [comment]
The xaringan slides are essentially HTML slides that we render to PNGs using `webshot::webshot`.  If you need to do something with animations, that's something you'd need to code up yourself.
