### ISSUE TITLE
Integrate open-source Text-to-Speech synthesizers

### ISSUE THREAD

**Issue by The-Pezman** [jhudsl/ari#32]
ARI is a great package, but I don't love the fact that its speech synthesis is dependent on Amazon. Not only does it complicate the setup process, it makes ARI less open source.

Adding an option for open-source speech synthesizers like [eSpeak](http://espeak.sourceforge.net), [Mycroft](https://mycroft.ai) and/or [MARYTTS](http://mary.dfki.de) would address this issue. They can all be easily downloaded and compiled on any OS, and have open licenses. Granted, I don't know how easy they are to call from R, but since they're written in C, I don't imagine it's terribly difficult.

Not all the voice options are great, but some are certainly adequate (at least in English). Adding additional mbrola voices could potentially help.

**Comment by muschellij2** [comment]
We use the text2speech package.  As per https://github.com/jhudsl/text2speech/issues/3, these can be incorporated only if an R package is already created.  "I don't imagine it's terribly difficult." - if that's true, then a welcomed PR to text2speech would allow us to use these.
